# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05f05f4991b116ac18b5170ceb1f7c086fa063dfc9a0d2071ed6398fd7245f2eaafda209280968c9e1f84785cefdc3da8abb510434bea1ffd505e265b10238c7

test:
  secret_key_base: 4c6243cc52e81def9a3ec7de1d06fe0d8bd07cf73ab80d4c3982c93b98f39225e4fb4fe2111c9ebe74447056fda6edb6b094df2c1ea9589a8a5965e770c2d8e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
